### ISSUE TITLE
Crowdfunder does not work on Bandit

### ISSUE THREAD

**Issue by Flexo013** [Moffein/RoR2-BanditClassic#5]
Pick up a Crowdfunder and notice that it does not render on his body. It causes lots of errors in the console. On top of that the Crowdfunder also isn't usable, due it not existing.

Maybe the Crowdfunder needs a set location for where on Bandit's body it will spawn?

**Comment by Moffein** [comment]
https://thunderstore.io/package/Moffein/BanditReloaded/
BanditClassic is no longer supported. BanditReloaded fixes the Crowdfunder issue. While gameplaywise BanditReloaded is pretty different from BanditClassic, tweaking the config can get it to feel pretty similar to BanditClassic.
